'use strict';
const COLORS = { math:'#0074FF', chemistry:'#66CCFF', physics:'#FFA500', english:'#FFFF00', social:'#00B000', other:'#FF0000', blue:'#0074FF', lightblue:'#66CCFF', orange:'#FFA500', yellow:'#FFFF00', green:'#00B000', gray:'#FF0000', red:'#FF0000' };
const NAMES = { math:'数学', chemistry:'化学', physics:'物理', english:'英語', social:'社会', other:'その他' };
function subject(key) { const normalized = String(key || '').replace('legacy-color:', ''); return { colorHex: COLORS[normalized] || '#FF0000', name: NAMES[normalized] || 'その他' }; }
function jstRange(days = 1) { const jst = new Date(Date.now() + 9*3600000); const start = new Date(jst); if (start.getUTCHours() < 2) start.setUTCDate(start.getUTCDate()-1); start.setUTCHours(2,0,0,0); return { start: new Date(start.getTime()-9*3600000-(days-1)*86400000), end: new Date(start.getTime()-9*3600000+86400000) }; }
async function intervals(db, guildId, start, end) { const r = await db.query(`SELECT user_id, category_key, task_name, start_at, end_at FROM activity_intervals WHERE is_active AND (guild_id=$1 OR guild_id='') AND start_at < $3 AND COALESCE(end_at, now()) > $2 ORDER BY start_at`, [guildId || '', start, end]); return r.rows.map(x => ({ ...x, startMs:new Date(x.start_at).getTime(), endMs:new Date(x.end_at || new Date()).getTime() })); }
function aggregate(rows, start, end) { const users = new Map(); const s=start.getTime(), e=end.getTime(); for (const row of rows) { const a=Math.max(s,row.startMs), b=Math.min(e,row.endMs); if (b<=a) continue; const info=subject(row.category_key); const item=users.get(row.user_id)||{userId:row.user_id,total:0,sessions:[],subjects:{}}; item.total+=b-a; item.sessions.push({start:a,end:b,colorHex:info.colorHex}); item.subjects[info.name]=(item.subjects[info.name]||0)+(b-a); users.set(row.user_id,item); } return [...users.values()].sort((a,b)=>b.total-a.total); }
function format(ms) { const m=Math.floor(ms/60000); return `${Math.floor(m/60)}時間${m%60}分`; }
module.exports={ intervals, aggregate, jstRange, subject, format };
